[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.0"
egui = "0.32.0"
image = "0.25"
core = { path = "../core" }
storage= { path = "../storage" }
tokio = { version = "1", features = ["rt"] }
rfd = "0.15.4"