[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.6.0"
core = { path = "../core" }

[[bench]]
name = "terrain_bench"
path = "benches/benches.rs"
harness = false